### ISSUE TITLE
Backend: authentication models

### ISSUE THREAD

**Issue by thrashches** [thrashches/kristall_backend#1]

**Comment by thrashches** [comment]
Набор urls:
- `api/v1/auth/mail/` - по почте
- `api/v1/auth/phone/` - по телефону
- `api/v1/auth/phone_confirm/` - отправка кода подтверждения
- `api/v1/vk/`
- `api/v1/google/`

### Авторизация по почте

input:
```json
{
  "email": "mail@email.com",
  "password": "string"
}
```
output `200 OK`:
```json
{
  "token": "string"
}
```
output `400 BAD REQUEST` неверный логин пароль:
```json
{
  "error": "string"
}
```
output `404 USER NOT FOUND` пользователь не найден:
```json
{
  "error": "string"
}
```

### Авторизация по телефону
Сначала шлем телефон на `api/v1/auth/phone/` формат "+79991234567":
```json
{
  "phone": "string"
}
```

Далее человек получив код идет на `api/v1/auth/phone_confirm/`:
```json
{
  "phone": "string",
  "code": "string"
}
```
Ошибки отрабатываем по той же схеме. Проблема со стороны юзера - 400.\
Если все хорошо, то `200 OK` и отдаем токен:
```json
{
  "token": "string"
}
```

**Comment by FedXL** [comment]
vk
{
"code": "string"
}

**Comment by FedXL** [comment]
google
{
"code":"string"
}

**Comment by FedXL** [comment]
Куда слать ошибки , если они возникнут при прохождении пути. ( проблемы с credenrtials) Ну не знаю. Протухли, забанили,ещё чё.

**Comment by FedXL** [comment]
links ( ссылки по которым надо отправлять пользователя при Oauth авторизации)

input: get
output:
{
"vk_url": "string",
 "google_url": "string"
}
